### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by asiviero76** [mrwolfjunior/zcsazzurro#1]
Hi
I try to import the flow, but I get 
[node: 0580e3373566f9d2]
msg : string[16]
"JSON parse error"

Don't know how to solve it

**Comment by mrwolfjunior** [comment]
Hi @asiviero76 

Unfortunately, ZCS changed the API header, now you must send also the "Client" parameter. I've updated the flow and instruction, try it and let me know

**Comment by asiviero76** [comment]
is working now, but also if I get the data, I cant see any data in homeassistant
<img width="1025" alt="Schermata 2022-07-06 alle 20 00 52" src="https://user-images.githubusercontent.com/108426198/177614125-d20ee96b-2553-4142-9d90-6ff9d3f04158.png">

**Comment by mrwolfjunior** [comment]
Ok awesome, take into consideration that you need to leave it running a couple of hours before home assistant is capable of giving you some graph. Also, I want to mention that on the first day you might have some strange data.

So, leave everything running and let me know 👍🏻

**Comment by asiviero76** [comment]
Thank you!

I see that now I can receive back the data from the request... but I really don't understand why I can't see the data into the dashboard of home assistant .... there is something more to do?


________________________________
Da: mrwolfjunior ***@***.***>
Inviato: mercoledì 6 luglio 2022 09:26
A: mrwolfjunior/zcsazzurro ***@***.***>
Cc: asiviero76 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [mrwolfjunior/zcsazzurro] not working (Issue #1)


Hi @asiviero76<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fasiviero76&data=05%7C01%7C%7Cc7332dc39c9b4b7fc2b408da5f20e2a6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637926892123274229%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tv0sEBaQFTrYGnJc4AtsVJ753z7Yg4bFJelNqyVlsz4%3D&reserved=0>

Unfortunately, ZCS changed the API header, now you must send also the "Client" parameter. I've updated the flow and instruction, try it and let me know
